logging:
  level:
    org.hibernate.orm.jdbc.bind: TRACE
    org.apache.coyote.http11: debug #Http 요청정보 로그 남기기

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER_CLASS_NAME}

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true

    hibernate:
      ddl-auto: create

cors:
  allowedOrigins: ${CORS_ALLOW_ORIGINS}

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirectUri: ${KAKAO_REDIRECT_URL}
    client_secret: ${KAKAO_CLIENT_SECRET}
    scope: ${KAKAO_SCOPE}
  naver:
    client_id: ${NAVER_CLIENT_ID}
    redirectUri: ${NAVER_REDIRECT_URL}
    client_secret: ${NAVER_CLIENT_SECRET}
    scope: ${NAVER_SCOPE}
    state: ${NAVER_STATE}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    redirectUri: ${GOOGLE_REDIRECT_URL}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    scope: ${GOOGLE_SCOPE}
