spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: embedded
      schema-locations:
        - classpath:sql/schema.sql
      data-locations:
        - classpath:sql/data.sql

logging:
  level:
    org.apache.coyote.http11: debug

server:
  servlet:
    session:
      tracking-modes: cookie
      timeout: 1800
