spring:
  profiles:
    active: local

server:
  servlet:
    contextPath: /api

oauth:
  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    redirect_uri: ${KAKAO_REDIRECT_URI}
    client_secret: ${KAKAO_CLIENT_SECRET}
    scope: ${KAKAO_SCOPE}
  naver:
    client_id: ${NAVER_CLIENT_ID}
    redirect_uri: ${NAVER_REDIRECT_URI}
    client_secret: ${NAVER_CLIENT_SECRET}
    scope: ${NAVER_SCOPE}
    state: ${NAVER_STATE}
  google:
    client_id: ${GOOGLE_CLIENT_ID}
    redirect_uri: ${GOOGLE_REDIRECT_URI}
    client_secret: ${GOOGLE_CLIENT_SECRET}
    scope: ${GOOGLE_SCOPE}
