name: ✨ Celuveat backend DEV CD ✨

on:
  push:
    branches:
      - develop-backend
    paths:
      - 'backend/**'
    
jobs:
  deploy-backend:
    runs-on: [self-hosted, dev]
        
    steps:
      - name: ✨ Run Backend Deploy Script 
        run: |
          cd ~
          sudo sh deploy-backend.sh
