name: ✨ Celuveat backend DEV CD ✨

on:
  push:
#     branches:
#       - develop-backend
#     paths:
#       - 'backend/**'
    
jobs:
  deploy-backend:
    runs-on: self-hosted
        
    steps:
      - name: ✨ Run Backend Deploy Script 
        run: |
          cd ~
          chmod 777 ./deploy-backend.sh
          sudo deploy-backend.sh
