name: ✨ Celuveat backend DEV CD ✨

on:
  push:
    branches:
      - develop-backend
    
jobs:
  deploy-backend:
    runs-on: [self-hosted, prod]
        
    steps:
      - name: ✨ Run Backend Deploy Script 
        run: |
          cd ~
          sudo sh deploy-backend.sh
