name: 🍔 E2E 테스트 🍔

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    name: 🍔테스트 딱 대라 💢👊

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: Write the cypress.env.json file 📝
        # use quotes around the secret, as its value
        # is simply inserted as a string into the command
        run: |
          echo '${{ secrets.CYPRESS_CONFIG_JSON }}' > cypress.env.json

      - name: 🍔 yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}

      # https://github.com/cypress-io/github-action
      - name: 🍔 E2E 테스트
        run: npx cypress run
        working-directory: ${{ env.working-directory }}
