name: 🍔 E2E 테스트 🍔

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./frontend

    name: 🍔테스트 딱 대라 💢👊

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: 🍔 yarn install
        run: pwd && ls && yarn install
        working-directory: ${{ env.working-directory }}

      # https://github.com/cypress-io/github-action
      - name: 🍔 E2E 테스트
        run: npx cypress run --env GOOGLE_EMAIL_FOR_TESTING=${{ secrets.GOOGLE_EMAIL_FOR_TESTING }},GOOGLE_PASSWORD_FOR_TESTING=${{ secrets.GOOGLE_PASSWORD_FOR_TESTING }}
        working-directory: ${{ env.working-directory }}
