name: 🍔 E2E 테스트 🍔

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E Test 딱 대라!
    env:
      working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: 🍔 yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: create-json
        id: create-json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: 'cypress.env.json'
          json: ${{ secrets.CYPRESS_CONFIG_JSON }}

      - name: 🍔 E2E 테스트
        run: pwd && ls && npx cypress run --browser chrome
        working-directory: ${{ env.working-directory }}
