name: 🍔 E2E 테스트 🍔

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    name: E2E Test 딱 대라!
    env:
      working-directory: ./frontend

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.1'

      - name: 🍔 Get npm cache directory
        id: npm-cache-dir
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
              - uses: actions/cache@v3

      - name: 🍔 Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> ${GITHUB_OUTPUT}
      - uses: actions/cache@v3
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: 🍔 yarn install
        run: yarn install
        working-directory: ${{ env.working-directory }}

      - name: 🍔 cypress env 설정
        env:
          GOOGLE_EMAIL_FOR_TESTING: ${{secrets.GOOGLE_EMAIL_FOR_TESTING}}
          GOOGLE_PASSWORD_FOR_TESTING: ${{secrets.GOOGLE_PASSWORD_FOR_TESTING}}
        run: |
          echo $GOOGLE_EMAIL_FOR_TESTING >> cypress.json
          echo $GOOGLE_PASSWORD_FOR_TESTING >> cypress.json

      - name: 🍔 E2E 테스트
        uses: cypress-io/github-action@v5
        with:
          working-directory: ${{ env.working-directory }}
          browser: chrome
