name: 🍔 Celuveat frontend DEV CD 🍔

on:
  push:
    branches:
      - develop-frontend
    paths:
      - 'frontend/**'

jobs:
  deploy-frontend:
    runs-on: self-hosted

    steps:
      - name: 🍔 .env 파일 세팅
        run: |
          touch ~/frontend-env/.env
          echo KAKAO_MAP_API_KEY=${{ secrets.KAKAO_MAP_API_KEY }} >> ~/frontend-env/.env

      - name: 🍔 Run Frontend Deploy Script
        run: |
          cd ~
          sudo sh deploy-frontend.sh
